from suning.api.govbus.AbcpayAddRequest import AbcpayAddRequest
from suning.api.govbus.AftersaleQueryRequest import AftersaleQueryRequest
from suning.api.govbus.AfterserviceQueryRequest import AfterserviceQueryRequest
from suning.api.govbus.AlipayCreateRequest import AlipayCreateRequest
from suning.api.govbus.ApplyexchangegoodsCreateRequest import ApplyexchangegoodsCreateRequest
from suning.api.govbus.ApplyRejectedAddRequest import ApplyRejectedAddRequest
from suning.api.govbus.ApplyrepairgoodsCreateRequest import ApplyrepairgoodsCreateRequest
from suning.api.govbus.BanktransferCreateRequest import BanktransferCreateRequest
from suning.api.govbus.BatchProdSaleStatusGetRequest import BatchProdSaleStatusGetRequest
from suning.api.govbus.CategoryGetRequest import CategoryGetRequest
from suning.api.govbus.CategorysearchQueryRequest import CategorysearchQueryRequest
from suning.api.govbus.CityGetRequest import CityGetRequest
from suning.api.govbus.CombinationProdQueryRequest import CombinationProdQueryRequest
from suning.api.govbus.ConfirmOrderAddRequest import ConfirmOrderAddRequest
from suning.api.govbus.CountyGetRequest import CountyGetRequest
from suning.api.govbus.EleinvoiceGetRequest import EleinvoiceGetRequest
from suning.api.govbus.FacProductConfirmRequest import FacProductConfirmRequest
from suning.api.govbus.FullAddressGetRequest import FullAddressGetRequest
from suning.api.govbus.GetbillQueryRequest import GetbillQueryRequest
from suning.api.govbus.GetcardsecretkeyQueryRequest import GetcardsecretkeyQueryRequest
from suning.api.govbus.GetinvoiceQueryRequest import GetinvoiceQueryRequest
from suning.api.govbus.GetmarkidinvoiceQueryRequest import GetmarkidinvoiceQueryRequest
from suning.api.govbus.GetperiodlimitQueryRequest import GetperiodlimitQueryRequest
from suning.api.govbus.GetproductclusterGetRequest import GetproductclusterGetRequest
from suning.api.govbus.GetspecialgoodsQueryRequest import GetspecialgoodsQueryRequest
from suning.api.govbus.IndividualeinvoiceQueryRequest import IndividualeinvoiceQueryRequest
from suning.api.govbus.InventoryGetRequest import InventoryGetRequest
from suning.api.govbus.InvoicebatchDeleteRequest import InvoicebatchDeleteRequest
from suning.api.govbus.InvoiceConfirmRequest import InvoiceConfirmRequest
from suning.api.govbus.InvoicelogistGetRequest import InvoicelogistGetRequest
from suning.api.govbus.InvoicesupplementConfirmRequest import InvoicesupplementConfirmRequest
from suning.api.govbus.JudgefacproductGetRequest import JudgefacproductGetRequest
from suning.api.govbus.LogistdetailGetRequest import LogistdetailGetRequest
from suning.api.govbus.LognumsubmitAddRequest import LognumsubmitAddRequest
from suning.api.govbus.MessageDeleteRequest import MessageDeleteRequest
from suning.api.govbus.MessageGetRequest import MessageGetRequest
from suning.api.govbus.MixconfirmorderAddRequest import MixconfirmorderAddRequest
from suning.api.govbus.MixpayorderAddRequest import MixpayorderAddRequest
from suning.api.govbus.MpStockQueryRequest import MpStockQueryRequest
from suning.api.govbus.OnlinepayCreateRequest import OnlinepayCreateRequest
from suning.api.govbus.OrderAccountQueryRequest import OrderAccountQueryRequest
from suning.api.govbus.OrderAcountQueryRequest import OrderAcountQueryRequest
from suning.api.govbus.OrderAddRequest import OrderAddRequest
from suning.api.govbus.OrdercancelDeleteRequest import OrdercancelDeleteRequest
from suning.api.govbus.OrderconfirmAddRequest import OrderconfirmAddRequest
from suning.api.govbus.OrderDetailGetRequest import OrderDetailGetRequest
from suning.api.govbus.OrderitemdetailGetRequest import OrderitemdetailGetRequest
from suning.api.govbus.OrderitemQueryRequest import OrderitemQueryRequest
from suning.api.govbus.OrderLogistGetRequest import OrderLogistGetRequest
from suning.api.govbus.OrderlogistnewGetRequest import OrderlogistnewGetRequest
from suning.api.govbus.OrdernumberGetRequest import OrdernumberGetRequest
from suning.api.govbus.OrdernumerQueryRequest import OrdernumerQueryRequest
from suning.api.govbus.OrderreconciliationQueryRequest import OrderreconciliationQueryRequest
from suning.api.govbus.OrderStatusGetRequest import OrderStatusGetRequest
from suning.api.govbus.PaymentwayGetRequest import PaymentwayGetRequest
from suning.api.govbus.PreDepositBalanceGetRequest import PreDepositBalanceGetRequest
from suning.api.govbus.PricemessageQueryRequest import PricemessageQueryRequest
from suning.api.govbus.PriceQueryRequest import PriceQueryRequest
from suning.api.govbus.ProdDetailGetRequest import ProdDetailGetRequest
from suning.api.govbus.ProdextendGetRequest import ProdextendGetRequest
from suning.api.govbus.ProdImageQueryRequest import ProdImageQueryRequest
from suning.api.govbus.ProdPoolQueryRequest import ProdPoolQueryRequest
from suning.api.govbus.ProdReviewQueryRequest import ProdReviewQueryRequest
from suning.api.govbus.ProductmappingQueryRequest import ProductmappingQueryRequest
from suning.api.govbus.ProductsearchQueryRequest import ProductsearchQueryRequest
from suning.api.govbus.ProvinceGetRequest import ProvinceGetRequest
from suning.api.govbus.RejectOrderDeleteRequest import RejectOrderDeleteRequest
from suning.api.govbus.RepairgoodsCancelRequest import RepairgoodsCancelRequest
from suning.api.govbus.RepairmethodQueryRequest import RepairmethodQueryRequest
from suning.api.govbus.RetchggoodsCancelRequest import RetchggoodsCancelRequest
from suning.api.govbus.ReturnpartorderAddRequest import ReturnpartorderAddRequest
from suning.api.govbus.ServiceratesGetRequest import ServiceratesGetRequest
from suning.api.govbus.ServicescheduleQueryRequest import ServicescheduleQueryRequest
from suning.api.govbus.SetsecretkeyUpdateRequest import SetsecretkeyUpdateRequest
from suning.api.govbus.ShipCarriageGetRequest import ShipCarriageGetRequest
from suning.api.govbus.ShipTimeGetRequest import ShipTimeGetRequest
from suning.api.govbus.SigninvoiceQueryRequest import SigninvoiceQueryRequest
from suning.api.govbus.SnorderidbythirdidQueryRequest import SnorderidbythirdidQueryRequest
from suning.api.govbus.SubcodeproductsGetRequest import SubcodeproductsGetRequest
from suning.api.govbus.TownGetRequest import TownGetRequest
from suning.api.govbus.UnionloginAddRequest import UnionloginAddRequest
from suning.api.govbus.UnpaidorderCancelRequest import UnpaidorderCancelRequest
