from suning.api.item.BookBrandQueryRequest import BookBrandQueryRequest
from suning.api.item.BookItemAddRequest import BookItemAddRequest
from suning.api.item.BookItemcontentsAddRequest import BookItemcontentsAddRequest
from suning.api.item.BookItemcontentsModifyRequest import BookItemcontentsModifyRequest
from suning.api.item.BookItemdetailQueryRequest import BookItemdetailQueryRequest
from suning.api.item.BookItemGetRequest import BookItemGetRequest
from suning.api.item.BookItemQueryRequest import BookItemQueryRequest
from suning.api.item.BookMainproductGetRequest import BookMainproductGetRequest
from suning.api.item.BookMainproductModifyRequest import BookMainproductModifyRequest
from suning.api.item.BookProductdetailQueryRequest import BookProductdetailQueryRequest
from suning.api.item.BookProductGetRequest import BookProductGetRequest
from suning.api.item.BookSalescatalogQueryRequest import BookSalescatalogQueryRequest
from suning.api.item.BrandQueryRequest import BrandQueryRequest
from suning.api.item.CategoryQueryRequest import CategoryQueryRequest
from suning.api.item.ChilditemAddRequest import ChilditemAddRequest
from suning.api.item.ItemAddRequest import ItemAddRequest
from suning.api.item.ItemcontentsAddRequest import ItemcontentsAddRequest
from suning.api.item.ItemcontentsModifyRequest import ItemcontentsModifyRequest
from suning.api.item.ItemDelorresRequest import ItemDelorresRequest
from suning.api.item.ItemDetailQueryRequest import ItemDetailQueryRequest
from suning.api.item.ItemGetRequest import ItemGetRequest
from suning.api.item.ItemparametersQueryRequest import ItemparametersQueryRequest
from suning.api.item.ItemQueryRequest import ItemQueryRequest
from suning.api.item.ItemsaleQueryRequest import ItemsaleQueryRequest
from suning.api.item.MainproductGetRequest import MainproductGetRequest
from suning.api.item.MainproductModifyRequest import MainproductModifyRequest
from suning.api.item.ModuleTempletGetRequest import ModuleTempletGetRequest
from suning.api.item.PicAddRequest import PicAddRequest
from suning.api.item.PicDeleteRequest import PicDeleteRequest
from suning.api.item.ProductdetailQueryRequest import ProductdetailQueryRequest
from suning.api.item.ProductGetRequest import ProductGetRequest
from suning.api.item.ProductQueryRequest import ProductQueryRequest
from suning.api.item.ShelvesAddRequest import ShelvesAddRequest
from suning.api.item.ShelvesMoveRequest import ShelvesMoveRequest
