from suning.api.oto.AddchildAddRequest import AddchildAddRequest
from suning.api.oto.CanshelvesQueryRequest import CanshelvesQueryRequest
from suning.api.oto.ExactsupplyapplyingQueryRequest import ExactsupplyapplyingQueryRequest
from suning.api.oto.FactoryinventoryModifyRequest import FactoryinventoryModifyRequest
from suning.api.oto.FactoryinventoryQueryRequest import FactoryinventoryQueryRequest
from suning.api.oto.InventoryGetRequest import InventoryGetRequest
from suning.api.oto.InventoryModifyRequest import InventoryModifyRequest
from suning.api.oto.ItemAddRequest import ItemAddRequest
from suning.api.oto.OrderGetRequest import OrderGetRequest
from suning.api.oto.OrderidsQueryRequest import OrderidsQueryRequest
from suning.api.oto.OrderinfoQueryRequest import OrderinfoQueryRequest
from suning.api.oto.PriceModifyRequest import PriceModifyRequest
from suning.api.oto.PriceQueryRequest import PriceQueryRequest
from suning.api.oto.PublishcmAddRequest import PublishcmAddRequest
from suning.api.oto.SalesstatusModifyRequest import SalesstatusModifyRequest
from suning.api.oto.SalesstatusQueryRequest import SalesstatusQueryRequest
from suning.api.oto.StoreAddRequest import StoreAddRequest
from suning.api.oto.StoregroupAddRequest import StoregroupAddRequest
from suning.api.oto.StoregrouprefAddRequest import StoregrouprefAddRequest
from suning.api.oto.StoreinfoQueryRequest import StoreinfoQueryRequest
from suning.api.oto.StoreModifyRequest import StoreModifyRequest
from suning.api.oto.StoreQueryRequest import StoreQueryRequest
from suning.api.oto.StorerelationQueryRequest import StorerelationQueryRequest
from suning.api.oto.SupplyapplyingAddRequest import SupplyapplyingAddRequest
from suning.api.oto.SupplyapplyingQueryRequest import SupplyapplyingQueryRequest
from suning.api.oto.WarehousepoolQueryRequest import WarehousepoolQueryRequest
from suning.api.oto.WarepoolcityagingQueryRequest import WarepoolcityagingQueryRequest
from suning.api.oto.WarepooldistrictagingQueryRequest import WarepooldistrictagingQueryRequest
