from suning.api.custom.AbnormalQueryRequest import AbnormalQueryRequest
from suning.api.custom.ActioneffectAddRequest import ActioneffectAddRequest
from suning.api.custom.ActivityallreleaseCancelRequest import ActivityallreleaseCancelRequest
from suning.api.custom.ActivitycouponCreateRequest import ActivitycouponCreateRequest
from suning.api.custom.ActivitycoupondetailGetRequest import ActivitycoupondetailGetRequest
from suning.api.custom.ActivitycouponGetRequest import ActivitycouponGetRequest
from suning.api.custom.ActivityexecCreateRequest import ActivityexecCreateRequest
from suning.api.custom.ActivityGetRequest import ActivityGetRequest
from suning.api.custom.ActivityidCreateRequest import ActivityidCreateRequest
from suning.api.custom.ActivityinfoQueryRequest import ActivityinfoQueryRequest
from suning.api.custom.ActivityQueryRequest import ActivityQueryRequest
from suning.api.custom.ActivityserviceDeleteRequest import ActivityserviceDeleteRequest
from suning.api.custom.ActivityserviceQueryRequest import ActivityserviceQueryRequest
from suning.api.custom.ActivityUpdateRequest import ActivityUpdateRequest
from suning.api.custom.AgreerefundConfirmRequest import AgreerefundConfirmRequest
from suning.api.custom.AgreereturnConfirmRequest import AgreereturnConfirmRequest
from suning.api.custom.AppointCreateRequest import AppointCreateRequest
from suning.api.custom.AppointQueryRequest import AppointQueryRequest
from suning.api.custom.AtmopicModifyRequest import AtmopicModifyRequest
from suning.api.custom.AuthorizeGetRequest import AuthorizeGetRequest
from suning.api.custom.BatchorderQueryRequest import BatchorderQueryRequest
from suning.api.custom.BookinginfoQueryRequest import BookinginfoQueryRequest
from suning.api.custom.BookitemGetRequest import BookitemGetRequest
from suning.api.custom.BookmainproductModifyRequest import BookmainproductModifyRequest
from suning.api.custom.CarbrandQueryRequest import CarbrandQueryRequest
from suning.api.custom.CarmodelQueryRequest import CarmodelQueryRequest
from suning.api.custom.CarnkQueryRequest import CarnkQueryRequest
from suning.api.custom.CarparameterReceiveRequest import CarparameterReceiveRequest
from suning.api.custom.CarseriesQueryRequest import CarseriesQueryRequest
from suning.api.custom.CategoryredictGetRequest import CategoryredictGetRequest
from suning.api.custom.childItemAddRequest import childItemAddRequest
from suning.api.custom.CodeGetRequest import CodeGetRequest
from suning.api.custom.ComposestrategyCreateRequest import ComposestrategyCreateRequest
from suning.api.custom.CrowdcountbystrategyidQueryRequest import CrowdcountbystrategyidQueryRequest
from suning.api.custom.CrowdcountbystrategyQueryRequest import CrowdcountbystrategyQueryRequest
from suning.api.custom.CulitemAddRequest import CulitemAddRequest
from suning.api.custom.CulitemcontentreviseModifyRequest import CulitemcontentreviseModifyRequest
from suning.api.custom.CulitemcontentsModifyRequest import CulitemcontentsModifyRequest
from suning.api.custom.CulitemdetailQueryRequest import CulitemdetailQueryRequest
from suning.api.custom.CustCreateRequest import CustCreateRequest
from suning.api.custom.DelayrefundModifyRequest import DelayrefundModifyRequest
from suning.api.custom.DeliverynewAddRequest import DeliverynewAddRequest
from suning.api.custom.DeliverytimeAddRequest import DeliverytimeAddRequest
from suning.api.custom.DicsingleQueryRequest import DicsingleQueryRequest
from suning.api.custom.DicwholeQueryRequest import DicwholeQueryRequest
from suning.api.custom.DireCouponAddRequest import DireCouponAddRequest
from suning.api.custom.EffectcouponQueryRequest import EffectcouponQueryRequest
from suning.api.custom.EffectflowQueryRequest import EffectflowQueryRequest
from suning.api.custom.EffectmsgGetRequest import EffectmsgGetRequest
from suning.api.custom.EffectorderQueryRequest import EffectorderQueryRequest
from suning.api.custom.ElectronicInvoiceAddRequest import ElectronicInvoiceAddRequest
from suning.api.custom.ExchangegoodsConfirmRequest import ExchangegoodsConfirmRequest
from suning.api.custom.ExchangegoodsdeliveryConfirmRequest import ExchangegoodsdeliveryConfirmRequest
from suning.api.custom.ExchangegoodsQueryRequest import ExchangegoodsQueryRequest
from suning.api.custom.ExchangemessagesQueryRequest import ExchangemessagesQueryRequest
from suning.api.custom.ExchangerefusereasonQueryRequest import ExchangerefusereasonQueryRequest
from suning.api.custom.FeaturewordModifyRequest import FeaturewordModifyRequest
from suning.api.custom.FmkcasdelivercouponCreateRequest import FmkcasdelivercouponCreateRequest
from suning.api.custom.freightTemplateAddRequest import freightTemplateAddRequest
from suning.api.custom.FreighttemplatenewUpdateRequest import FreighttemplatenewUpdateRequest
from suning.api.custom.GalaxiecouponGetRequest import GalaxiecouponGetRequest
from suning.api.custom.GetproductcodeQueryRequest import GetproductcodeQueryRequest
from suning.api.custom.GotoappointCreateRequest import GotoappointCreateRequest
from suning.api.custom.GrantUpdateRequest import GrantUpdateRequest
from suning.api.custom.GshoppingcartQueryRequest import GshoppingcartQueryRequest
from suning.api.custom.GuacouponCreateRequest import GuacouponCreateRequest
from suning.api.custom.GuacouponModifyRequest import GuacouponModifyRequest
from suning.api.custom.GuacouponQueryRequest import GuacouponQueryRequest
from suning.api.custom.HeadpicandnicknameQueryRequest import HeadpicandnicknameQueryRequest
from suning.api.custom.historyOrderQueryQueryRequest import historyOrderQueryQueryRequest
from suning.api.custom.IntegralCreateRequest import IntegralCreateRequest
from suning.api.custom.IntegralDeleteRequest import IntegralDeleteRequest
from suning.api.custom.IntegraldetailQueryRequest import IntegraldetailQueryRequest
from suning.api.custom.InteractactivityCancelRequest import InteractactivityCancelRequest
from suning.api.custom.InteractactivityCreateRequest import InteractactivityCreateRequest
from suning.api.custom.InteractactivityeffectQueryRequest import InteractactivityeffectQueryRequest
from suning.api.custom.InteractactivityGetRequest import InteractactivityGetRequest
from suning.api.custom.InteractactivityQueryRequest import InteractactivityQueryRequest
from suning.api.custom.InteractactivityUpdateRequest import InteractactivityUpdateRequest
from suning.api.custom.InteractstoreeffectQueryRequest import InteractstoreeffectQueryRequest
from suning.api.custom.invaddressQueryRequest import invaddressQueryRequest
from suning.api.custom.InvbalanceGetRequest import InvbalanceGetRequest
from suning.api.custom.inventoryGetRequest import inventoryGetRequest
from suning.api.custom.InvmacinfoGetRequest import InvmacinfoGetRequest
from suning.api.custom.InvoiceinfoGetRequest import InvoiceinfoGetRequest
from suning.api.custom.InvoiceQueryRequest import InvoiceQueryRequest
from suning.api.custom.InvorderReceiveRequest import InvorderReceiveRequest
from suning.api.custom.InvoverstockGetRequest import InvoverstockGetRequest
from suning.api.custom.ItemDetailQueryRequest import ItemDetailQueryRequest
from suning.api.custom.itemSaleQueryRequest import itemSaleQueryRequest
from suning.api.custom.JudgeproductConfirmRequest import JudgeproductConfirmRequest
from suning.api.custom.LabelstrategyCreateRequest import LabelstrategyCreateRequest
from suning.api.custom.ListsignQueryRequest import ListsignQueryRequest
from suning.api.custom.ListtemplateQueryRequest import ListtemplateQueryRequest
from suning.api.custom.logisticCompanyQueryRequest import logisticCompanyQueryRequest
from suning.api.custom.LogisticsOrderGetRequest import LogisticsOrderGetRequest
from suning.api.custom.LsypriceModifyRequest import LsypriceModifyRequest
from suning.api.custom.LsypriceQueryRequest import LsypriceQueryRequest
from suning.api.custom.MainpicvideoUpdateRequest import MainpicvideoUpdateRequest
from suning.api.custom.MembindModifyRequest import MembindModifyRequest
from suning.api.custom.MemgrowupGetRequest import MemgrowupGetRequest
from suning.api.custom.MemlabelsQueryRequest import MemlabelsQueryRequest
from suning.api.custom.MemlevelGetRequest import MemlevelGetRequest
from suning.api.custom.MemlevelruleQueryRequest import MemlevelruleQueryRequest
from suning.api.custom.MemrightGetRequest import MemrightGetRequest
from suning.api.custom.MerOrderDirectAddRequest import MerOrderDirectAddRequest
from suning.api.custom.MessageQueryRequest import MessageQueryRequest
from suning.api.custom.MixcustnumGetRequest import MixcustnumGetRequest
from suning.api.custom.MobileCouponAddRequest import MobileCouponAddRequest
from suning.api.custom.MobileCouponModifyRequest import MobileCouponModifyRequest
from suning.api.custom.MobileCouponQueryRequest import MobileCouponQueryRequest
from suning.api.custom.MobileRecommendAddRequest import MobileRecommendAddRequest
from suning.api.custom.MobileRecommendModifyRequest import MobileRecommendModifyRequest
from suning.api.custom.MobileRecommendQueryRequest import MobileRecommendQueryRequest
from suning.api.custom.MobileSequenceModifyRequest import MobileSequenceModifyRequest
from suning.api.custom.MobileSequenceQueryRequest import MobileSequenceQueryRequest
from suning.api.custom.MsgtaskCancelRequest import MsgtaskCancelRequest
from suning.api.custom.MsgtaskCreateRequest import MsgtaskCreateRequest
from suning.api.custom.MsgtaskGetRequest import MsgtaskGetRequest
from suning.api.custom.NewbrandQueryRequest import NewbrandQueryRequest
from suning.api.custom.NicknameGetRequest import NicknameGetRequest
from suning.api.custom.NormDeleteRequest import NormDeleteRequest
from suning.api.custom.NormModifyRequest import NormModifyRequest
from suning.api.custom.NPicAddRequest import NPicAddRequest
from suning.api.custom.OneorderGetRequest import OneorderGetRequest
from suning.api.custom.orderDeliveryAddRequest import orderDeliveryAddRequest
from suning.api.custom.orderGetGetRequest import orderGetGetRequest
from suning.api.custom.OrderidQueryRequest import OrderidQueryRequest
from suning.api.custom.orderNoteModifyRequest import orderNoteModifyRequest
from suning.api.custom.orderQueryQueryRequest import orderQueryQueryRequest
from suning.api.custom.orderSelfDistAddRequest import orderSelfDistAddRequest
from suning.api.custom.OrdersQueryRequest import OrdersQueryRequest
from suning.api.custom.OrdmodtimeQueryRequest import OrdmodtimeQueryRequest
from suning.api.custom.OtoinfoModifyRequest import OtoinfoModifyRequest
from suning.api.custom.parallelInventoryGetRequest import parallelInventoryGetRequest
from suning.api.custom.PicdetechAddRequest import PicdetechAddRequest
from suning.api.custom.PicdetechGetRequest import PicdetechGetRequest
from suning.api.custom.PicdirectoryAddRequest import PicdirectoryAddRequest
from suning.api.custom.PicdirectoryDeleteRequest import PicdirectoryDeleteRequest
from suning.api.custom.PicdirectoryQueryRequest import PicdirectoryQueryRequest
from suning.api.custom.PicfilesQueryRequest import PicfilesQueryRequest
from suning.api.custom.PictureAddRequest import PictureAddRequest
from suning.api.custom.PictureDeleteRequest import PictureDeleteRequest
from suning.api.custom.PrescriptionConfirmRequest import PrescriptionConfirmRequest
from suning.api.custom.prescriptionParamsQueryRequest import prescriptionParamsQueryRequest
from suning.api.custom.PriceExclusiveAddRequest import PriceExclusiveAddRequest
from suning.api.custom.PriceExclusiveGetRequest import PriceExclusiveGetRequest
from suning.api.custom.PriceExclusiveModifyRequest import PriceExclusiveModifyRequest
from suning.api.custom.PriceExclusiveQueryRequest import PriceExclusiveQueryRequest
from suning.api.custom.PriceUpdateRequest import PriceUpdateRequest
from suning.api.custom.ProductoperateAddRequest import ProductoperateAddRequest
from suning.api.custom.ProductoperateConfirmRequest import ProductoperateConfirmRequest
from suning.api.custom.ProductoperateDeleteRequest import ProductoperateDeleteRequest
from suning.api.custom.ProductoperateQueryRequest import ProductoperateQueryRequest
from suning.api.custom.ProductsaleareaAddRequest import ProductsaleareaAddRequest
from suning.api.custom.ProductsaleareaQueryRequest import ProductsaleareaQueryRequest
from suning.api.custom.PxcardReceiveRequest import PxcardReceiveRequest
from suning.api.custom.PxcardstatusReceiveRequest import PxcardstatusReceiveRequest
from suning.api.custom.PzxxdatainfoGetRequest import PzxxdatainfoGetRequest
from suning.api.custom.queryElectronicInvoiceGetRequest import queryElectronicInvoiceGetRequest
from suning.api.custom.RefundAddRequest import RefundAddRequest
from suning.api.custom.RefundinformationQueryRequest import RefundinformationQueryRequest
from suning.api.custom.RefundlistinformationQueryRequest import RefundlistinformationQueryRequest
from suning.api.custom.RefundmessagesConfirmRequest import RefundmessagesConfirmRequest
from suning.api.custom.RefundmessagesQueryRequest import RefundmessagesQueryRequest
from suning.api.custom.RejectexchangedeliverModifyRequest import RejectexchangedeliverModifyRequest
from suning.api.custom.RejectexchangeModifyRequest import RejectexchangeModifyRequest
from suning.api.custom.RejectrefundModifyRequest import RejectrefundModifyRequest
from suning.api.custom.RejectreturnModifyRequest import RejectreturnModifyRequest
from suning.api.custom.ReportQueryRequest import ReportQueryRequest
from suning.api.custom.ReserveInfoQueryRequest import ReserveInfoQueryRequest
from suning.api.custom.reSmsSendRequest import reSmsSendRequest
from suning.api.custom.ReturngoodsQueryRequest import ReturngoodsQueryRequest
from suning.api.custom.ReturnorderGetRequest import ReturnorderGetRequest
from suning.api.custom.RewardbindAddRequest import RewardbindAddRequest
from suning.api.custom.SalesManageModifyRequest import SalesManageModifyRequest
from suning.api.custom.SendgoodsModifyRequest import SendgoodsModifyRequest
from suning.api.custom.SensitivewordsConfirmRequest import SensitivewordsConfirmRequest
from suning.api.custom.ShopfavoriteAddRequest import ShopfavoriteAddRequest
from suning.api.custom.ShopfavoritedGetRequest import ShopfavoritedGetRequest
from suning.api.custom.ShopinfoModifyRequest import ShopinfoModifyRequest
from suning.api.custom.ShopinfoQueryRequest import ShopinfoQueryRequest
from suning.api.custom.ShoplabelsQueryRequest import ShoplabelsQueryRequest
from suning.api.custom.ShoppingcartCreateRequest import ShoppingcartCreateRequest
from suning.api.custom.SignatureAddRequest import SignatureAddRequest
from suning.api.custom.SignatureDeleteRequest import SignatureDeleteRequest
from suning.api.custom.SignatureGetRequest import SignatureGetRequest
from suning.api.custom.SignaturewhiteAddRequest import SignaturewhiteAddRequest
from suning.api.custom.SignaturewhiteDeleteRequest import SignaturewhiteDeleteRequest
from suning.api.custom.SignaturewhiteQueryRequest import SignaturewhiteQueryRequest
from suning.api.custom.SingleinventoryGetRequest import SingleinventoryGetRequest
from suning.api.custom.SlssAddRequest import SlssAddRequest
from suning.api.custom.StorageQueryRequest import StorageQueryRequest
from suning.api.custom.StoredeclareinformationQueryRequest import StoredeclareinformationQueryRequest
from suning.api.custom.StoregroupAddRequest import StoregroupAddRequest
from suning.api.custom.StoregrouplistQueryRequest import StoregrouplistQueryRequest
from suning.api.custom.StoregroupQueryRequest import StoregroupQueryRequest
from suning.api.custom.StrategyDeleteRequest import StrategyDeleteRequest
from suning.api.custom.StrategyGetRequest import StrategyGetRequest
from suning.api.custom.StrategyinstanceCreateRequest import StrategyinstanceCreateRequest
from suning.api.custom.StrategyportraitQueryRequest import StrategyportraitQueryRequest
from suning.api.custom.StrategyQueryRequest import StrategyQueryRequest
from suning.api.custom.SuncodeCreateRequest import SuncodeCreateRequest
from suning.api.custom.SupplieraccountinfoQueryRequest import SupplieraccountinfoQueryRequest
from suning.api.custom.SupplieractivityAddRequest import SupplieractivityAddRequest
from suning.api.custom.SupplieractivityCreateRequest import SupplieractivityCreateRequest
from suning.api.custom.SyncinventoryModifyRequest import SyncinventoryModifyRequest
from suning.api.custom.TaskresultGetRequest import TaskresultGetRequest
from suning.api.custom.TemplateAddRequest import TemplateAddRequest
from suning.api.custom.TemplateDeleteRequest import TemplateDeleteRequest
from suning.api.custom.TemplateGetRequest import TemplateGetRequest
from suning.api.custom.TicketsReceiveRequest import TicketsReceiveRequest
from suning.api.custom.unpaidOrderQueryRequest import unpaidOrderQueryRequest
from suning.api.custom.UpdatevideomesModifyRequest import UpdatevideomesModifyRequest
from suning.api.custom.VedioModifyRequest import VedioModifyRequest
from suning.api.custom.verificationInfoModifyRequest import verificationInfoModifyRequest
from suning.api.custom.VideobatchReceiveRequest import VideobatchReceiveRequest
from suning.api.custom.VirtualConfirmRequest import VirtualConfirmRequest
from suning.api.custom.VirtualGetRequest import VirtualGetRequest
from suning.api.custom.VisiteffectAddRequest import VisiteffectAddRequest
