from suning.api.fourps.BrandMasDataQueryRequest import BrandMasDataQueryRequest
from suning.api.fourps.CategoryMasDataQueryRequest import CategoryMasDataQueryRequest
from suning.api.fourps.CelStorageSubAddRequest import CelStorageSubAddRequest
from suning.api.fourps.CelStorageSubGetRequest import CelStorageSubGetRequest
from suning.api.fourps.CelStorageSubQueryRequest import CelStorageSubQueryRequest
from suning.api.fourps.ExpressorderAddRequest import ExpressorderAddRequest
from suning.api.fourps.ExpressorderQueryRequest import ExpressorderQueryRequest
from suning.api.fourps.InventoryDetailGetRequest import InventoryDetailGetRequest
from suning.api.fourps.InventoryQuantityGetRequest import InventoryQuantityGetRequest
from suning.api.fourps.ItemAddRequest import ItemAddRequest
from suning.api.fourps.ItemDeleteRequest import ItemDeleteRequest
from suning.api.fourps.ItemDetailGetRequest import ItemDetailGetRequest
from suning.api.fourps.ItemInfoGetRequest import ItemInfoGetRequest
from suning.api.fourps.ItemInfoQueryRequest import ItemInfoQueryRequest
from suning.api.fourps.ItemModifyRequest import ItemModifyRequest
from suning.api.fourps.RealCelStorageGetRequest import RealCelStorageGetRequest
from suning.api.fourps.RealStorageQueryRequest import RealStorageQueryRequest
from suning.api.fourps.RefundWorkInfoDeleteRequest import RefundWorkInfoDeleteRequest
from suning.api.fourps.ResultAddRequest import ResultAddRequest
from suning.api.fourps.StoragesubAddRequest import StoragesubAddRequest
from suning.api.fourps.StoragesubGetRequest import StoragesubGetRequest
from suning.api.fourps.StorageSubQueryRequest import StorageSubQueryRequest
