from suning.api.integrate.childItemAddRequest import childItemAddRequest
from suning.api.integrate.CulitemAddRequest import CulitemAddRequest
from suning.api.integrate.CulitemcontentreviseModifyRequest import CulitemcontentreviseModifyRequest
from suning.api.integrate.CulitemcontentsModifyRequest import CulitemcontentsModifyRequest
from suning.api.integrate.ItemAddRequest import ItemAddRequest
from suning.api.integrate.itemContentsAddRequest import itemContentsAddRequest
from suning.api.integrate.itemContentsModifyRequest import itemContentsModifyRequest
from suning.api.integrate.ItemdetailQueryRequest import ItemdetailQueryRequest
from suning.api.integrate.itemSaleQueryRequest import itemSaleQueryRequest
from suning.api.integrate.PriceModifyRequest import PriceModifyRequest
from suning.api.integrate.PriceQueryRequest import PriceQueryRequest
from suning.api.integrate.queryCulitemdetailGetRequest import queryCulitemdetailGetRequest
