from suning.api.custom.AbnormalQueryTest import AbnormalQueryTest
from suning.api.custom.ActioneffectAddTest import ActioneffectAddTest
from suning.api.custom.ActivityallreleaseCancelTest import ActivityallreleaseCancelTest
from suning.api.custom.ActivitycouponCreateTest import ActivitycouponCreateTest
from suning.api.custom.ActivitycoupondetailGetTest import ActivitycoupondetailGetTest
from suning.api.custom.ActivitycouponGetTest import ActivitycouponGetTest
from suning.api.custom.ActivityexecCreateTest import ActivityexecCreateTest
from suning.api.custom.ActivityGetTest import ActivityGetTest
from suning.api.custom.ActivityidCreateTest import ActivityidCreateTest
from suning.api.custom.ActivityinfoQueryTest import ActivityinfoQueryTest
from suning.api.custom.ActivityQueryTest import ActivityQueryTest
from suning.api.custom.ActivityserviceDeleteTest import ActivityserviceDeleteTest
from suning.api.custom.ActivityserviceQueryTest import ActivityserviceQueryTest
from suning.api.custom.ActivityUpdateTest import ActivityUpdateTest
from suning.api.custom.AgreerefundConfirmTest import AgreerefundConfirmTest
from suning.api.custom.AgreereturnConfirmTest import AgreereturnConfirmTest
from suning.api.custom.AppointCreateTest import AppointCreateTest
from suning.api.custom.AppointQueryTest import AppointQueryTest
from suning.api.custom.AtmopicModifyTest import AtmopicModifyTest
from suning.api.custom.AuthorizeGetTest import AuthorizeGetTest
from suning.api.custom.BatchorderQueryTest import BatchorderQueryTest
from suning.api.custom.BookinginfoQueryTest import BookinginfoQueryTest
from suning.api.custom.BookitemGetTest import BookitemGetTest
from suning.api.custom.BookmainproductModifyTest import BookmainproductModifyTest
from suning.api.custom.CarbrandQueryTest import CarbrandQueryTest
from suning.api.custom.CarmodelQueryTest import CarmodelQueryTest
from suning.api.custom.CarnkQueryTest import CarnkQueryTest
from suning.api.custom.CarparameterReceiveTest import CarparameterReceiveTest
from suning.api.custom.CarseriesQueryTest import CarseriesQueryTest
from suning.api.custom.CategoryredictGetTest import CategoryredictGetTest
from suning.api.custom.childItemAddTest import childItemAddTest
from suning.api.custom.CodeGetTest import CodeGetTest
from suning.api.custom.ComposestrategyCreateTest import ComposestrategyCreateTest
from suning.api.custom.CrowdcountbystrategyidQueryTest import CrowdcountbystrategyidQueryTest
from suning.api.custom.CrowdcountbystrategyQueryTest import CrowdcountbystrategyQueryTest
from suning.api.custom.CulitemAddTest import CulitemAddTest
from suning.api.custom.CulitemcontentreviseModifyTest import CulitemcontentreviseModifyTest
from suning.api.custom.CulitemcontentsModifyTest import CulitemcontentsModifyTest
from suning.api.custom.CulitemdetailQueryTest import CulitemdetailQueryTest
from suning.api.custom.CustCreateTest import CustCreateTest
from suning.api.custom.DelayrefundModifyTest import DelayrefundModifyTest
from suning.api.custom.DeliverynewAddTest import DeliverynewAddTest
from suning.api.custom.DeliverytimeAddTest import DeliverytimeAddTest
from suning.api.custom.DicsingleQueryTest import DicsingleQueryTest
from suning.api.custom.DicwholeQueryTest import DicwholeQueryTest
from suning.api.custom.DireCouponAddTest import DireCouponAddTest
from suning.api.custom.EffectcouponQueryTest import EffectcouponQueryTest
from suning.api.custom.EffectflowQueryTest import EffectflowQueryTest
from suning.api.custom.EffectmsgGetTest import EffectmsgGetTest
from suning.api.custom.EffectorderQueryTest import EffectorderQueryTest
from suning.api.custom.ElectronicInvoiceAddTest import ElectronicInvoiceAddTest
from suning.api.custom.ExchangegoodsConfirmTest import ExchangegoodsConfirmTest
from suning.api.custom.ExchangegoodsdeliveryConfirmTest import ExchangegoodsdeliveryConfirmTest
from suning.api.custom.ExchangegoodsQueryTest import ExchangegoodsQueryTest
from suning.api.custom.ExchangemessagesQueryTest import ExchangemessagesQueryTest
from suning.api.custom.ExchangerefusereasonQueryTest import ExchangerefusereasonQueryTest
from suning.api.custom.FeaturewordModifyTest import FeaturewordModifyTest
from suning.api.custom.FmkcasdelivercouponCreateTest import FmkcasdelivercouponCreateTest
from suning.api.custom.freightTemplateAddTest import freightTemplateAddTest
from suning.api.custom.FreighttemplatenewUpdateTest import FreighttemplatenewUpdateTest
from suning.api.custom.GalaxiecouponGetTest import GalaxiecouponGetTest
from suning.api.custom.GetproductcodeQueryTest import GetproductcodeQueryTest
from suning.api.custom.GotoappointCreateTest import GotoappointCreateTest
from suning.api.custom.GrantUpdateTest import GrantUpdateTest
from suning.api.custom.GshoppingcartQueryTest import GshoppingcartQueryTest
from suning.api.custom.GuacouponCreateTest import GuacouponCreateTest
from suning.api.custom.GuacouponModifyTest import GuacouponModifyTest
from suning.api.custom.GuacouponQueryTest import GuacouponQueryTest
from suning.api.custom.HeadpicandnicknameQueryTest import HeadpicandnicknameQueryTest
from suning.api.custom.historyOrderQueryQueryTest import historyOrderQueryQueryTest
from suning.api.custom.IntegralCreateTest import IntegralCreateTest
from suning.api.custom.IntegralDeleteTest import IntegralDeleteTest
from suning.api.custom.IntegraldetailQueryTest import IntegraldetailQueryTest
from suning.api.custom.InteractactivityCancelTest import InteractactivityCancelTest
from suning.api.custom.InteractactivityCreateTest import InteractactivityCreateTest
from suning.api.custom.InteractactivityeffectQueryTest import InteractactivityeffectQueryTest
from suning.api.custom.InteractactivityGetTest import InteractactivityGetTest
from suning.api.custom.InteractactivityQueryTest import InteractactivityQueryTest
from suning.api.custom.InteractactivityUpdateTest import InteractactivityUpdateTest
from suning.api.custom.InteractstoreeffectQueryTest import InteractstoreeffectQueryTest
from suning.api.custom.invaddressQueryTest import invaddressQueryTest
from suning.api.custom.InvbalanceGetTest import InvbalanceGetTest
from suning.api.custom.inventoryGetTest import inventoryGetTest
from suning.api.custom.InvmacinfoGetTest import InvmacinfoGetTest
from suning.api.custom.InvoiceinfoGetTest import InvoiceinfoGetTest
from suning.api.custom.InvoiceQueryTest import InvoiceQueryTest
from suning.api.custom.InvorderReceiveTest import InvorderReceiveTest
from suning.api.custom.InvoverstockGetTest import InvoverstockGetTest
from suning.api.custom.ItemDetailQueryTest import ItemDetailQueryTest
from suning.api.custom.itemSaleQueryTest import itemSaleQueryTest
from suning.api.custom.JudgeproductConfirmTest import JudgeproductConfirmTest
from suning.api.custom.LabelstrategyCreateTest import LabelstrategyCreateTest
from suning.api.custom.ListsignQueryTest import ListsignQueryTest
from suning.api.custom.ListtemplateQueryTest import ListtemplateQueryTest
from suning.api.custom.logisticCompanyQueryTest import logisticCompanyQueryTest
from suning.api.custom.LogisticsOrderGetTest import LogisticsOrderGetTest
from suning.api.custom.LsypriceModifyTest import LsypriceModifyTest
from suning.api.custom.LsypriceQueryTest import LsypriceQueryTest
from suning.api.custom.MainpicvideoUpdateTest import MainpicvideoUpdateTest
from suning.api.custom.MembindModifyTest import MembindModifyTest
from suning.api.custom.MemgrowupGetTest import MemgrowupGetTest
from suning.api.custom.MemlabelsQueryTest import MemlabelsQueryTest
from suning.api.custom.MemlevelGetTest import MemlevelGetTest
from suning.api.custom.MemlevelruleQueryTest import MemlevelruleQueryTest
from suning.api.custom.MemrightGetTest import MemrightGetTest
from suning.api.custom.MerOrderDirectAddTest import MerOrderDirectAddTest
from suning.api.custom.MessageQueryTest import MessageQueryTest
from suning.api.custom.MixcustnumGetTest import MixcustnumGetTest
from suning.api.custom.MobileCouponAddTest import MobileCouponAddTest
from suning.api.custom.MobileCouponModifyTest import MobileCouponModifyTest
from suning.api.custom.MobileCouponQueryTest import MobileCouponQueryTest
from suning.api.custom.MobileRecommendAddTest import MobileRecommendAddTest
from suning.api.custom.MobileRecommendModifyTest import MobileRecommendModifyTest
from suning.api.custom.MobileRecommendQueryTest import MobileRecommendQueryTest
from suning.api.custom.MobileSequenceModifyTest import MobileSequenceModifyTest
from suning.api.custom.MobileSequenceQueryTest import MobileSequenceQueryTest
from suning.api.custom.MsgtaskCancelTest import MsgtaskCancelTest
from suning.api.custom.MsgtaskCreateTest import MsgtaskCreateTest
from suning.api.custom.MsgtaskGetTest import MsgtaskGetTest
from suning.api.custom.NewbrandQueryTest import NewbrandQueryTest
from suning.api.custom.NicknameGetTest import NicknameGetTest
from suning.api.custom.NormDeleteTest import NormDeleteTest
from suning.api.custom.NormModifyTest import NormModifyTest
from suning.api.custom.NPicAddTest import NPicAddTest
from suning.api.custom.OneorderGetTest import OneorderGetTest
from suning.api.custom.orderDeliveryAddTest import orderDeliveryAddTest
from suning.api.custom.orderGetGetTest import orderGetGetTest
from suning.api.custom.OrderidQueryTest import OrderidQueryTest
from suning.api.custom.orderNoteModifyTest import orderNoteModifyTest
from suning.api.custom.orderQueryQueryTest import orderQueryQueryTest
from suning.api.custom.orderSelfDistAddTest import orderSelfDistAddTest
from suning.api.custom.OrdersQueryTest import OrdersQueryTest
from suning.api.custom.OrdmodtimeQueryTest import OrdmodtimeQueryTest
from suning.api.custom.OtoinfoModifyTest import OtoinfoModifyTest
from suning.api.custom.parallelInventoryGetTest import parallelInventoryGetTest
from suning.api.custom.PicdetechAddTest import PicdetechAddTest
from suning.api.custom.PicdetechGetTest import PicdetechGetTest
from suning.api.custom.PicdirectoryAddTest import PicdirectoryAddTest
from suning.api.custom.PicdirectoryDeleteTest import PicdirectoryDeleteTest
from suning.api.custom.PicdirectoryQueryTest import PicdirectoryQueryTest
from suning.api.custom.PicfilesQueryTest import PicfilesQueryTest
from suning.api.custom.PictureAddTest import PictureAddTest
from suning.api.custom.PictureDeleteTest import PictureDeleteTest
from suning.api.custom.PrescriptionConfirmTest import PrescriptionConfirmTest
from suning.api.custom.prescriptionParamsQueryTest import prescriptionParamsQueryTest
from suning.api.custom.PriceExclusiveAddTest import PriceExclusiveAddTest
from suning.api.custom.PriceExclusiveGetTest import PriceExclusiveGetTest
from suning.api.custom.PriceExclusiveModifyTest import PriceExclusiveModifyTest
from suning.api.custom.PriceExclusiveQueryTest import PriceExclusiveQueryTest
from suning.api.custom.PriceUpdateTest import PriceUpdateTest
from suning.api.custom.ProductoperateAddTest import ProductoperateAddTest
from suning.api.custom.ProductoperateConfirmTest import ProductoperateConfirmTest
from suning.api.custom.ProductoperateDeleteTest import ProductoperateDeleteTest
from suning.api.custom.ProductoperateQueryTest import ProductoperateQueryTest
from suning.api.custom.ProductsaleareaAddTest import ProductsaleareaAddTest
from suning.api.custom.ProductsaleareaQueryTest import ProductsaleareaQueryTest
from suning.api.custom.PxcardReceiveTest import PxcardReceiveTest
from suning.api.custom.PxcardstatusReceiveTest import PxcardstatusReceiveTest
from suning.api.custom.PzxxdatainfoGetTest import PzxxdatainfoGetTest
from suning.api.custom.queryElectronicInvoiceGetTest import queryElectronicInvoiceGetTest
from suning.api.custom.RefundAddTest import RefundAddTest
from suning.api.custom.RefundinformationQueryTest import RefundinformationQueryTest
from suning.api.custom.RefundlistinformationQueryTest import RefundlistinformationQueryTest
from suning.api.custom.RefundmessagesConfirmTest import RefundmessagesConfirmTest
from suning.api.custom.RefundmessagesQueryTest import RefundmessagesQueryTest
from suning.api.custom.RejectexchangedeliverModifyTest import RejectexchangedeliverModifyTest
from suning.api.custom.RejectexchangeModifyTest import RejectexchangeModifyTest
from suning.api.custom.RejectrefundModifyTest import RejectrefundModifyTest
from suning.api.custom.RejectreturnModifyTest import RejectreturnModifyTest
from suning.api.custom.ReportQueryTest import ReportQueryTest
from suning.api.custom.ReserveInfoQueryTest import ReserveInfoQueryTest
from suning.api.custom.reSmsSendTest import reSmsSendTest
from suning.api.custom.ReturngoodsQueryTest import ReturngoodsQueryTest
from suning.api.custom.ReturnorderGetTest import ReturnorderGetTest
from suning.api.custom.RewardbindAddTest import RewardbindAddTest
from suning.api.custom.SalesManageModifyTest import SalesManageModifyTest
from suning.api.custom.SendgoodsModifyTest import SendgoodsModifyTest
from suning.api.custom.SensitivewordsConfirmTest import SensitivewordsConfirmTest
from suning.api.custom.ShopfavoriteAddTest import ShopfavoriteAddTest
from suning.api.custom.ShopfavoritedGetTest import ShopfavoritedGetTest
from suning.api.custom.ShopinfoModifyTest import ShopinfoModifyTest
from suning.api.custom.ShopinfoQueryTest import ShopinfoQueryTest
from suning.api.custom.ShoplabelsQueryTest import ShoplabelsQueryTest
from suning.api.custom.ShoppingcartCreateTest import ShoppingcartCreateTest
from suning.api.custom.SignatureAddTest import SignatureAddTest
from suning.api.custom.SignatureDeleteTest import SignatureDeleteTest
from suning.api.custom.SignatureGetTest import SignatureGetTest
from suning.api.custom.SignaturewhiteAddTest import SignaturewhiteAddTest
from suning.api.custom.SignaturewhiteDeleteTest import SignaturewhiteDeleteTest
from suning.api.custom.SignaturewhiteQueryTest import SignaturewhiteQueryTest
from suning.api.custom.singleGetRejectedGetTest import singleGetRejectedGetTest
from suning.api.custom.SingleinventoryGetTest import SingleinventoryGetTest
from suning.api.custom.SlssAddTest import SlssAddTest
from suning.api.custom.StorageQueryTest import StorageQueryTest
from suning.api.custom.StoredeclareinformationQueryTest import StoredeclareinformationQueryTest
from suning.api.custom.StoregroupAddTest import StoregroupAddTest
from suning.api.custom.StoregrouplistQueryTest import StoregrouplistQueryTest
from suning.api.custom.StoregroupQueryTest import StoregroupQueryTest
from suning.api.custom.StrategyDeleteTest import StrategyDeleteTest
from suning.api.custom.StrategyGetTest import StrategyGetTest
from suning.api.custom.StrategyinstanceCreateTest import StrategyinstanceCreateTest
from suning.api.custom.StrategyportraitQueryTest import StrategyportraitQueryTest
from suning.api.custom.StrategyQueryTest import StrategyQueryTest
from suning.api.custom.SuncodeCreateTest import SuncodeCreateTest
from suning.api.custom.SupplieraccountinfoQueryTest import SupplieraccountinfoQueryTest
from suning.api.custom.SupplieractivityAddTest import SupplieractivityAddTest
from suning.api.custom.SupplieractivityCreateTest import SupplieractivityCreateTest
from suning.api.custom.SyncinventoryModifyTest import SyncinventoryModifyTest
from suning.api.custom.TaskresultGetTest import TaskresultGetTest
from suning.api.custom.TemplateAddTest import TemplateAddTest
from suning.api.custom.TemplateDeleteTest import TemplateDeleteTest
from suning.api.custom.TemplateGetTest import TemplateGetTest
from suning.api.custom.TicketsReceiveTest import TicketsReceiveTest
from suning.api.custom.unpaidOrderQueryTest import unpaidOrderQueryTest
from suning.api.custom.UpdatevideomesModifyTest import UpdatevideomesModifyTest
from suning.api.custom.VedioModifyTest import VedioModifyTest
from suning.api.custom.verificationInfoModifyTest import verificationInfoModifyTest
from suning.api.custom.VideobatchReceiveTest import VideobatchReceiveTest
from suning.api.custom.VirtualConfirmTest import VirtualConfirmTest
from suning.api.custom.VirtualGetTest import VirtualGetTest
from suning.api.custom.VisiteffectAddTest import VisiteffectAddTest
