from suning.api.saleoff.AddchildAddRequest import AddchildAddRequest
from suning.api.saleoff.CmmdtyinfoModifyRequest import CmmdtyinfoModifyRequest
from suning.api.saleoff.ElectronicsheetAddRequest import ElectronicsheetAddRequest
from suning.api.saleoff.ItemAddRequest import ItemAddRequest
from suning.api.saleoff.ItemcontentsQueryRequest import ItemcontentsQueryRequest
from suning.api.saleoff.MainproductGetRequest import MainproductGetRequest
from suning.api.saleoff.MainproductModifyRequest import MainproductModifyRequest
from suning.api.saleoff.MylibarybatchQueryRequest import MylibarybatchQueryRequest
from suning.api.saleoff.MylibaryQueryRequest import MylibaryQueryRequest
from suning.api.saleoff.PriceModifyRequest import PriceModifyRequest
from suning.api.saleoff.PriceQueryRequest import PriceQueryRequest
from suning.api.saleoff.PublishcmAddRequest import PublishcmAddRequest
