from suning.api.shop.DsrInfoGetRequest import DsrInfoGetRequest
from suning.api.shop.ShopcategoryAddRequest import ShopcategoryAddRequest
from suning.api.shop.ShopcategoryDeleteRequest import ShopcategoryDeleteRequest
from suning.api.shop.ShopCategoryItemAddRequest import ShopCategoryItemAddRequest
from suning.api.shop.ShopCategoryItemDeleteRequest import ShopCategoryItemDeleteRequest
from suning.api.shop.ShopCategoryItemQueryRequest import ShopCategoryItemQueryRequest
from suning.api.shop.ShopCategoryModifyRequest import ShopCategoryModifyRequest
from suning.api.shop.ShopcategoryQueryRequest import ShopcategoryQueryRequest
from suning.api.shop.ShopInfoGetRequest import ShopInfoGetRequest
from suning.api.shop.ShopInfoModifyRequest import ShopInfoModifyRequest
