from suning.api.cloudinfo.ChatContentQueryRequest import ChatContentQueryRequest
from suning.api.cloudinfo.ChatUserQueryRequest import ChatUserQueryRequest
from suning.api.cloudinfo.CustInStatusQueryRequest import CustInStatusQueryRequest
from suning.api.cloudinfo.CustOpinionGetRequest import CustOpinionGetRequest
from suning.api.cloudinfo.SubAccountQueryRequest import SubAccountQueryRequest
